version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data
      - neo4j_data:/logs
    networks:
      - my_network

  app:
    build: ./app
    depends_on:
      - neo4j
#        condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - my_network

volumes:
  neo4j_data:

networks:
  my_network:
    driver: bridge